threads: 8
batchSize: 100

binlog:
    serverId: 1
    host: "127.0.0.1"
    port: 33061
    user: "root"
    password: ""
    gtid: "e5a93cbc-1707-11e9-9a21-0242ac110002"
    position: "1-26"

source:
    addr: "127.0.0.1:33061"
    user: "root"
    password: ""
    db: "transaction_base"
    tls: false

target:
    addr: "127.0.0.1:33062"
    user: "root"
    password: ""
    db: "transaction_base"
    tls: false

schemas:
    transaction_base:
        - table: users
          batch: 0
          fieldId: user_id
          latest: 0
          interval: 90h
        - table: transactions
          batch: 1000
          cleanAfter: 1s
          fieldId: trx_id
          latest: 0
        - table: transaction_params
          batch: 1000
          cleanAfter: 1s
          fieldId: id_tansaction
          latest: 0
        - table: transaction_type
          interval: 90h
          fieldId: type_id
          batch: 0
          latest: 0
        - table: transaction_status
          interval: 90h
          batch: 0
          fieldId: status_id
          latest: 0
        - table: transaction_param_types
          interval: 90h
          fieldId: id_param_type
          batch: 0
          latest: 0
